[general]
import = [
  "~/.config/alacritty/themes/themes/noctis_lux.toml"
]

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[font]
size = 14.0
normal = { family = "iMWritingMono Nerd Font" }

[font.offset]
x = 2
y = 1
