# Automatically start tmux
# Check if the tmux command exists and if we're not already in a tmux session
if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
  # Attempt to attach to a session. If none exists, create a new one.
  tmux attach || tmux new-session
fi
